### ISSUE TITLE
Release example code under similar Apache 2.0 License?

### ISSUE THREAD

**Issue by mithro** [MicrochipTech/mla_usb#1]
Firstly, it is awesome that you have released this USB stack under the Apache 2.0 license!

However, it appears that all the example code for using this USB stack is only available under the MLA license. Any chance you could release these example applications under an Apache 2.0 License too?

**Comment by davidflowers** [comment]
We intend to.  It is just a matter of time and figuring out how to best distribute it.

**Comment by mithro** [comment]
That is awesome to hear! 

Do you have any time line? (Are we talking weeks, months or years?)

Your approach here with the mla_usb seems pretty good. Having it in a GitHub repo makes it easier to fork and modify.

**Comment by davidflowers** [comment]
It would be weeks at a minimum, probably a few months at a maximum.

The distribution we need to determine is if we distribute the demos in the same repo as the core or a separate repo(s).  There are pros and cons to each approach and we are considering which method we think works best for our situation.

**Comment by mithro** [comment]
Thanks for your reply! Just a FYI, it is easier to merge two repositories after the fact then it is to split a repository in half. I would recommend going with a fine grain approach (separate repos) and then merging them if you find it too unwieldy.

Great to see @MicrochipTech really committing to open source! Hopefully you can win some of those Arduino developers. Your chips have always been _much_ better value for money and your samples program way more awesome.

Excited long term (since roughly 2004!) PIC user :)

**Comment by mithro** [comment]
Any luck?

**Comment by davidflowers** [comment]
The files are all ready for the next release which is tentatively scheduled for April.

**Comment by davidflowers** [comment]
The Apache licensed demo files should be live now at [www.microchip.com/mla](url).  We'll be pushing the stack files merge out in the next week to this location.  Having a separate external repo for the demos is still TBD.
