### ISSUE TITLE
Open to external contributions?

### ISSUE THREAD

**Issue by mithro** [MicrochipTech/mla_usb#2]
Hello @davidflowers,

I was wondering if you are interested in pull requests to improve the code in this repository? I have two things I would like to do it;

 * Remove all the trailing whitespace on the end of lines.
 * Add support for the sdcc compiler.

Would you be open to these contributions?

Thanks!

Tim @mithro Ansell

**Comment by davidflowers** [comment]
Tim,

We are open to contributions.  I haven't been merging in the last few releases from the internal repo as there didn't appear to be much interest here on github.  I can merge in the latest files then you can submit a pull request and I will check out the changes.

Give me a few days to merge in the latest release.

Thanks,
David

**Comment by mithro** [comment]
@davidflowers Great! Looking forward to it.

**Comment by davidflowers** [comment]
Done.  I've also merged in a bug fix that we received after the final release cut was built so this currently mirrors our internal repo exactly at this moment in time.

**Comment by sebcaux** [comment]
Thank you very much, we can update this submodule in our repository.
